### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by vseloved** [lisp/de.setf.thrift#1]
Hi James,

I'm trying to use this library in a slightly uncommon way: just to serialize data (the purpose is to compare different serialization methods, like: protocol-buffers, bson etc).

For that I use a simple example of a file-system hierarchy, that can be expressed in sexp form like this:

```
("root" :owner "root" :group "adm" :rights (7 5 5)
  ("docs" :owner "root" :group "adm" :rights (7 5 5)
    ("article.pdf" :owner "root" :group "adm" :rights (6 4 4)
                   "This is a sample article. It's rather short")
    ("example.pdf" :owner "root" :group "adm" :rights (6 4 4)
                   "123456")
    ("example.pdf~" :owner "root" :group "adm" :rights (6 4 0)
                    "And this is a backup of example.pdf")))
```

I've tried to implement it with the following structures:

```
(thrift:def-enum "node-type"
  (("FILE" . 1)
   ("DIR"  . 2)))

 (thrift:def-struct "rights"
   ((u 0 :type 'byte :id 1)
    (g 0 :type 'byte :id 2)
    (o 0 :type 'byte :id 3)))

 (thrift:def-struct "node"
  ((type nil :type 'node-type :id 1)
   (name nil :type 'string :id 2)
   (owner nil :type 'string :id 3)
   (group nil :type 'string :id 4)
   (rights nil :type 'rights :id 5)
   (content nil :type 'string :optional t :id 6)
   (nodes nil :type '(list node) :optional t :id 7)))
```

Then I've tried to encode them in binary form with thrift:stream-write-struct, but it failed (with the following error: There is no applicable method for the generic function #<STANDARD-GENERIC-FUNCTION ORG.APACHE.THRIFT.IMPLEMENTATION::STREAM-WRITE-FIELD-BEGIN (1)> when called with arguments (#<ORG.APACHE.THRIFT:BINARY-PROTOCOL {B43ED99}> TYPE 'NODE-TYPE 1).)

After a lot of searching I came to the conclusion, that Thrift in general and its client libraries (like this one in particular) really lack in terms of good and rich examples of IDL definitions and usage.  Maybe, you could spend some time to create such example, using my data as a starting point?  Or at least provide clues, how to move forward, and I'll try to create the example myself.

Thanks!
Vsevolod

**Comment by lisp** [comment]
did your searching take you to the cassandra repository?
this library was implemented in order to support that.
thrift's primary use is via idl-based specs which are translated to the target language.
no value judgement, that's just the way it is.
there are also several things in the test directory which may help you if you want to write either thrift or clos definitions yourself.

when i tried your definitions, once they are syntactically correct, they work in principle. there is a bug which prevents a complete roundtrip, but that is secondary to your problem. once you get that far, your will need to add a method to delegate from the protocol to its transport to read bytes.

once you have looked at the cassandra code, feel free to get back in touch if you still have questions.
